# action.yml
name: 'Chainsaw=CDXGen'
description: 'Generating SBOM'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - run: cd $GITHUB_WORKSPACE && docker run --rm -v /tmp:/tmp -v $(pwd):/app:rw -t ghcr.io/cyclonedx/cdxgen -r /app -o /app/bom.json
      shell: bash
    - run: cd $GITHUB_WORKSPACE && docker run -v ${PWD}:/src ghcr.io/google/osv-scanner --sbom=src/bom.json --format json --output src/scan-results.json
      shell: bash
    - run: cd $GITHUB_WORKSPACE && cat scan-results.json
      shell: bash